package:
    name: genomedisco
    version: 0.1

source:
    git_url: https://github.com/kundajelab/genomedisco

requirements:
    build:
        - python
        - setuptools
        - numpy >=1.9
        - matplotlib <=1.5.3
        - scikit-learn
    run:
        - python
        - numpy >=1.9
        - scikit-learn
        - matplotlib <=1.5.3
        
	
